from .schematic_overlay import NODE_CLASS_MAPPINGS as _OVERLAY_CLASSES
from .schematic_overlay import NODE_DISPLAY_NAME_MAPPINGS as _OVERLAY_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(_OVERLAY_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(_OVERLAY_NAMES)
