from .schematic_overlay import NODE_CLASS_MAPPINGS as _OVERLAY_CLASSES
from .schematic_overlay import NODE_DISPLAY_NAME_MAPPINGS as _OVERLAY_NAMES
from .schematic_voronoi import NODE_CLASS_MAPPINGS as _VORONOI_CLASSES
from .schematic_voronoi import NODE_DISPLAY_NAME_MAPPINGS as _VORONOI_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(_OVERLAY_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(_OVERLAY_NAMES)
NODE_CLASS_MAPPINGS.update(_VORONOI_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(_VORONOI_NAMES)
